name: Bugs Report
description: Please fill out this template with all the relevant information so we can debug your issue.
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill your bug report.
        Please fill out the following information:
  - type: textarea
    id: Description
    attributes:
      label: Describe the bug
      description: And please tell us what did you expect to happen.
    validation:
      required: true
  - type: textarea
    id: Version
    attributes:
      label: Version
      description: What version of dpp are you running? (use `dpp --version` to get it)
    validation:
      required: true
  - type: textarea
    id: Steps to reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide a minimal reproducible example of the bug.
    validation:
      required: false
  - type: dropdown
    id: OS
    attributes:
      label: OS
      options:
        - Windows
        - MacOS
        - Linux(Debian-based)
        - Other
    validation:
      required: true
  - type: textarea
    id: Additional context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.