name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up cmake
      uses: lukka/get-cmake@latest

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: boost-json boost-filesystem boost-serialization boost-program-options antlr4 fmt
        token: ${{ github.token }}
        triplet: x64-linux-release
        github-binarycache: true

    - name: Build project
      run: |
        cd tools
        python build.py --debug --vcpkg-root ${{ steps.vcpkg.outputs.vcpkg-root }} --build

  build-windows7:
    name: Build on Windows 7
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up cmake
      uses: lukka/get-cmake@latest

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: boost-json boost-filesystem boost-serialization boost-program-options antlr4 fmt
        token: ${{ github.token }}
        triplet: x64-windows-release
        github-binarycache: true

    - name: Build project
      run: |
        cd tools
        python build.py --debug --vcpkg-root ${{ steps.vcpkg.outputs.vcpkg-root }} --build

  build-windows-latest:
    name: Build on Latest Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up cmake
      uses: lukka/get-cmake@latest

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: boost-json boost-filesystem boost-serialization boost-program-options antlr4 fmt
        token: ${{ github.token }}
        triplet: x64-windows-release
        github-binarycache: true

    - name: Build project
      run: |
        cd tools
        python build.py --debug --vcpkg-root ${{ steps.vcpkg.outputs.vcpkg-root }} --build