name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up vcpkg
      uses: microsoft/vcpkg-action@v12
      with:
        vcpkg-root: ${{ github.workspace }}/vcpkg

    - name: Install dependencies with vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg install boost-program-options boost-json boost-filesystem boost-serialization fmt antlr4

    - name: Build project
      run: |
        cd tools
        python build.py

  build-windows7:
    name: Build on Windows 7
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up vcpkg
      uses: microsoft/vcpkg-action@v12
      with:
        vcpkg-root: ${{ github.workspace }}/vcpkg

    - name: Install dependencies with vcpkg
      run: |
        ${{ github.workspace }}\vcpkg\vcpkg.exe install boost-program-options boost-json boost-filesystem boost-serialization fmt antlr4

    - name: Build project
      run: |
        cd tools
        python build.py

  build-windows-latest:
    name: Build on Latest Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up vcpkg
      uses: microsoft/vcpkg-action@v12
      with:
        vcpkg-root: ${{ github.workspace }}/vcpkg

    - name: Install dependencies with vcpkg
      run: |
        ${{ github.workspace }}\vcpkg\vcpkg.exe install boost-program-options boost-json boost-serialization boost-filesystem fmt antlr4

    - name: Build project
      run: |
        cd tools
        python build.py