name: Build and Release
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone vcpkg
        run: git clone https://github.com/Microsoft/vcpkg.git

      - name: Install dependencies with vcpkg
        working-directory: vcpkg
        run:./bootstrap-vcpkg.sh &&./vcpkg install boost-serialization && ./vcpkg install boost-json && ./vcpkg install boost-program-options &&./vcpkg install boost-filesystem &&./vcpkg install boost-test && ./vcpkg install fmt && ./vcpkg install antlr4
      - name: Build source code
        run: cd DPP && cd tools && python build.py --release

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: 'Release ${{ github.ref_name }}'
