name: Build and Release
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: lukka/get-cmake@latest

      - name: Install dependencies with vcpkg
        uses: lukka/run-vcpkg@v11
      - name: Build source code
        run: cd DPP && cd tools && python build.py --release

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: 'Release ${{ github.ref_name }}'
