name: Build

on:
  push:
    branches:
      - main
      - dev
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]



jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest] # Systems to build for
        arch: [x86_64, arm64] # Architectures to build for
      fail-fast: false
    runs-on: ${{matrix.os}}
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Set Arch
      run: |
        xmake f -a ${{matrix.arch}} -y

    - name: Build project
      run: |
        xmake build -y

    - name: Run tests
      run: |
        xmake run tests


    - name: Package project
      run: |
        xmake pack -y -o packages/

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ./packages
        overwrite: true

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          body: New Release.
          draft: true
          fail_on_unmatched_files: true
          files: |
              ./packages/*
