name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]



jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build project
      run: |
        xmake build -y

    - name: Run tests
      run: |
        xmake run tests


    - name: Package project
      run: |
        xmake pack -y

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          body: New Release.
          draft: true
          fail_on_unmatched_files: true
          files: |
            build/xpack/DPP/*
