name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up cmake
      uses: lukka/get-cmake@latest

    - name: Setup Cpp
      uses: aminya/setup-cpp@v1
      with:
        compiler: gcc

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        pkgs: boost-serialization boost-program-options antlr4 jsoncpp termcolor
        token: ${{ github.token }}
        triplet: x64-linux
        github-binarycache: true

    - name: Build project
      run: |
        cd tools
        python build.py --release --no-vcpkg-root ${{steps.vcpkg.outputs.vcpkg-cmake-config}} --build

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-project
        path: ${{github.workspace}}/
