name: Build

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Build project
      run: |
        xmake build -y

    - name: Package project
      run: |
        xmake pack -y

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-project
        path: ${{github.workspace}}/build/xpack/DPP/**
